### PR TITLE
Add jq to ubuntu

### PR DESCRIPTION
**Pull request by alexjh**

### CODE REVIEW

**Comment by mook-as** [comment]
As far as I can tell, the actual pipeline is using the `merged_stemcells` branch.

**Comment by alexjh** [comment]
Yeah, I'm scratching my head about how this gets built and tested. Maybe @aduffeck or @jimmykarily can tell us?

I chose `opensuse_stemcell` because that's the default branch for this repo.

I pushed `stemcells-check` pipeline, and it's looking at the `opensuse_stemcell_with_patched_go_agent` branch?

**Comment by cornelius** [comment]
Why is `jq` needed in the stemcell?

And this is a change to the ubuntu step, does that influence the SUSE stemcell at all?

As this is changing the Ubuntu stemcell this probably should be an upstream change. Maybe even in general as we don't want to sit on a fork if we can avoid it in any way.

And we do need to clean up forks and branches of the stemcell builder, but that's another story.

**Comment by alexjh** [comment]
`jq` is needed for some setup scripts in SCF: https://github.com/SUSE/scf/issues/1081

* https://github.com/SUSE/scf/blob/develop/container-host-files/etc/scf/config/scripts/configure-HA-hosts.sh
* https://github.com/SUSE/scf/blob/7df8ddcd6849743430476b37b2c7e6bf433162e1/src/scf-helper-release/jobs/uaa-create-user/templates/run.erb#L165

I'll look into whether we can replace those instances with something else already on the Ubuntu stemcell, and remove `jq` from the SUSE stemcells.

**Comment by alexjh** [comment]
Closing as there were only two uses of `jq` that I could find, and they can be replaced.

**Pull request closed without merging**
